### ISSUE TITLE
Parse date with ordinals

### ISSUE THREAD

**Issue by wezm** [wezm/rsspls#16]
These dates fail to parse:

```
 WARN  rsspls > unable to parse date 'Sunday, April 18th, 2021'
 WARN  rsspls > unable to parse date 'Friday, January 8th, 2021'
 WARN  rsspls > unable to parse date 'Tuesday, September 15th, 2020'
 WARN  rsspls > unable to parse date 'Monday, April 6th, 2020'
 WARN  rsspls > unable to parse date 'Friday, March 13th, 2020'
 WARN  rsspls > unable to parse date 'Sunday, June 2nd, 2019'
 WARN  rsspls > unable to parse date 'Wednesday, May 29th, 2019'
 WARN  rsspls > unable to parse date 'Saturday, May 25th, 2019'
 WARN  rsspls > unable to parse date 'Thursday, May 16th, 2019'
 WARN  rsspls > unable to parse date 'Tuesday, May 7th, 2019'
 WARN  rsspls > unable to parse date 'Friday, April 26th, 2019'
 WARN  rsspls > unable to parse date 'Tuesday, April 23rd, 2019'
 WARN  rsspls > unable to parse date 'Wednesday, April 17th, 2019'
```

**Comment by bruno-cobucci** [comment]
Hello, I've been getting some trouble with dates too, just not ordinals.

``` 
 WARN  rsspls > unable to parse date '17/01/2023'
 WARN  rsspls > unable to parse date '16/01/2023'
 WARN  rsspls > unable to parse date '13/01/2023'
 WARN  rsspls > unable to parse date '13/01/2023'
 WARN  rsspls > unable to parse date '13/01/2023'
 WARN  rsspls > unable to parse date '30/12/2022'
 WARN  rsspls > unable to parse date '30/12/2022'
```

I'm trying to create a feed using this page (in portuguese): https://www.gov.br/capes/pt-br/assuntos/noticias
Eveything is generated corretly, except for the dates. It seems that it might be struggling to parse dates there are in the DD/MM/YYYY format? As opposed to MM/DD/YYYY, used in US.

**Comment by wezm** [comment]
I used [anydate](https://lib.rs/crates/anydate) for date parsing. I think I need to add the option of manually specifying the date format for the cases that it doesn't handle automatically.

**Comment by wezm** [comment]
@bruno-cobucci Just to keep you updated, I'm working on making it possible to specify the expected date format, which should allow the dates on the page you're fetching to be parsed.

**Comment by bruno-cobucci** [comment]
Thank you for your help and for your great software! I'm in a research team in humanities and when I told them about this program they were really excited. It's helping us in a big way.
