### ISSUE TITLE
Adding Media selector

### ISSUE THREAD

**Issue by Lcchy** [wezm/rsspls#28]
Hi,

I would like to contribute the addition of a media selector so that a media url can be read from the website and included as an enclosure into the output RSS feed.

Would you be open for a PR?

Enclosure specification:
- https://www.rssboard.org/rss-draft-1#element-channel-item-enclosure
- https://en.wikipedia.org/wiki/RSS_enclosure

**Comment by wezm** [comment]
Interesting idea. Happy to accept an PR for this functionality.

**Comment by Lcchy** [comment]
Cool! I just opened the PR
