### ISSUE TITLE
Optional media

### ISSUE THREAD

**Issue by wezm** [wezm/rsspls#31]
If a `media` selector is specified it's currently required that all items match this selector, otherwise the feed will not generate. Since the enclosure is an optional element in the feed I think it would make sense to skip the enclosure if the media selector does not match anything. What do you think @Lcchy?

**Comment by Lcchy** [comment]
Yes I agree with this, and I think we could even go as far as skipping an item that raises any error during parsing, log it, and continue the items parsing loop.

This would be more robust in general and with the logging the user would still be able to see what is being dropped.

I already adapted the code for this and could open a PR if you're interested. I am currently using this as a website I am scraping has certain ad items mixed in that do not match on my `title` selector, so they get automatically dropped.

**Comment by wezm** [comment]
The reason I didn't do it this way initially is that I run `rsspls` unattended. I.e. it runs on a server and I never see the logs. However if it fails and exits with an error that is more noticeable to me (although honestly not by much). Having said that it probably does make sense to keep going as much as it can, so feel free to open the PR.

**Comment by Lcchy** [comment]
Cool, will do.
If any errors are encountered, they will be logged to stderr and then the user can decide what to do with it?
We could also change the return code to reflect a partially successful execution.
