### ISSUE TITLE
feature request: enable multi page source

### ISSUE THREAD

**Issue by aborruso** [wezm/rsspls#48]
Hi,
a lot of time I have this kind of input URL:
https://servizi.comune.barcellonapozzodigotto.me.it/barcellona/mc/mc_p_ricerca.php?multiente=barcellona&pag=1

Only 7 items per page. Updates happen with a certain frequency, so should I increase the frequency, or leave it the same and increase the number items.
To increase this number I must query `pag=2` and `pag=3`. Of course, without changing any other parameters.

It would be nice to have the option to put multiple requests together in one output xml.

I currently make it with three configurations and then merge all with xmlstarlet.

Thank you

**Comment by wezm** [comment]
> Only 7 items per page. Updates happen with a certain frequency, so should I increase the frequency, or leave it the same and increase the number items.

I can't check myself, see below. There's no place on the page to increase the number of items per page? Polling at a rate that catches all new items seems like a straightforward solution, is there a reason that doesn't work for you?

![image](https://github.com/wezm/rsspls/assets/21787/3e614819-3537-4f5d-85fe-0361692c819d)

**Comment by aborruso** [comment]
> I can't check myself, see below. There's no place on the page to increase the number of items per page?

Hi, there is no place.

> Polling at a rate that catches all new items seems like a straightforward solution, is there a reason that doesn't work for you?

Reduced risk of blocking, and sometimes I had difficulty managing on one machine multiple cronjobs.
