### ISSUE TITLE
Feature request: Local file access

### ISSUE THREAD

**Issue by vdun** [wezm/rsspls#55]
Currently trying to access 'file://tmp/z.htm' would result in :
```
INFO  rsspls::feed > processing file://tmp/z.htm
ERROR rsspls       > error processing feed for file://tmp/z.htm

Caused by:
0: unable to fetch file://tmp/z.htm
1: builder error for url (file://tmp/z.htm): URL scheme is not allowed
2: URL scheme is not allowed
```

**Comment by wezm** [comment]
@vdun I've merged support for this. Are you able to build from `main` to test this? If not, I can publish a pre-release binary for you to test if that works.
