### ISSUE TITLE
builder error: URL scheme is not allowed

### ISSUE THREAD

**Issue by mach-o** [wezm/rsspls#61]
I'm not sure if this is a bug report or feature request, but when I try to build an rss feed from an xml file I'm getting the following error:

 ERROR rsspls       > error processing feed for file:///[local path]/A-245-24.xml
Caused by:
   0: unable to fetch file:///[local path]/A-245-24.xml
   1: builder error for url (file:///[local path]/A-245-24.xml): URL scheme is not allowed
   2: URL scheme is not allowed

My situation is this: I'd like an RSS feed of court filings in certain proceedings before the Federal Court of Canada . You can look these up by court file number on the court website, but it does this through some javascript stuff, and essentially just feeds the browser all of the necessary information through an easy to identify JSON GET request.

I've set up a crontab to pull the JSON to a local file, then transmute JSON to XML, then I tried to have rsspls create a feed out of the resulting XML, with the error message above as the result. 

In case more specifics would help, the URL for the JSON GET is:

https://www.fct-cf.gc.ca/CourtFilesAndDecisions/proceedingQueriesRE?division=A-245-24&courtnumber=A-245-24

And then I'm just  trying to do:

item = "data"
heading = "RECORDED_ENTRY"
summary = "DOCNO"
date = "FILING_DATE"

Thanks!

**Comment by wezm** [comment]
Do you have [file-urls](https://rsspls.7bit.org/documentation/#file-urls) enabled at the top of the config file? E.g.

```toml
[rsspls]
output = "/some/path"
file_urls = true
```

**Comment by mach-o** [comment]
Yes, I do

**Comment by wezm** [comment]
Hmm it's going down the http code path, not the file path for some reason. Just to confirm some things:

- What OS are you using and now did you install rsspls?
- What's the output of `rsspls --version`?

**Comment by mach-o** [comment]
I'm using Ubuntu v24.04.01. It's been a while since I installed rsspls but it looks like I just downloaded the linux binary and put it into a contrib/bin type directory in $PATH.

$ rsspls --version
rsspls version 0.8.1

Looks like the current version is 0.10 based on the website so maybe that is my problem, I'll give an "upgrade" a shot.

**Comment by mach-o** [comment]
Yes, that seemed to fix this problem! I'm now getting a properly formed feed with no items, which still was not the desired output, but that is presumably also something on my end. Thanks! Incidentally I don't suppose there is an rss feed to follow new versions of rsspls so I don't fall behind again, is there?

**Comment by mach-o** [comment]
Yes, getting a weird error there but I'll open a new issue since it's unrelated.

**Comment by wezm** [comment]
> Yes, that seemed to fix this problem! 

Right, the file url support was only added in the 0.10 release.
